name: Test Suite
on: [pull_request]

jobs:
  lint-unit:
    name: Lint, Unit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.8, 3.9, 3.10]
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
    - name: Install Dependencies
      run: |
        pip install tox
    - name: Lint
      run: tox -vve lint
    - name: Unit Tests
      run: tox -vve unit
